---
- name: php-cli | Timezoneの設定
  lineinfile: dest={{ php.dest_cli }}
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: php-cli | opcacheの有効化
  lineinfile: dest={{ php.dest_cli }}
              regexp=';?opcache.enable_cli=\d'
              line='opcache.enable_cli=1'

- name: php-cli | moduleソケットの追加
  lineinfile:
    dest: "{{ php.dest_cli }}"
    line: "extension={{ item }}.so"
  with_items:
      - "{{ php.modules }}"
  when: modules is defined

- name: php-cli | php.iniの編集
  lineinfile:
    dest: "{{ php.dest_cli }}"
    #正規表現内のバックスラッシュが使えるように
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ php.config_changes }}"
